---
output: bookdown::word_document2
---

## Watershed characteristics as predictors for DOC and NOM	

```{r, include = FALSE, package.startup.message = FALSE}

# load required packages
library(tidyverse)  # keep it tidy
library(readr)      # read in delimited files
library(knitr)      # for nice tables

knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=FALSE, fig.cap=TRUE)

```


### Introduction
__RQ.3.__   Are some watershed characteristics more important than others for influencing DOC and NOM dynamics?

__Objective 3:__   Assess the importance of watershed characteristics and conditions as explanatory variables for DOC and DOM patterns.


#### Random Forests

A collection of decision trees is a Random Forest, which play an important role for both predictive modeling and inference purposes. 

The Breiman's Random Forests (RF) is a machine learning algorithm for practical applications, which is popular for its accuracy in real-world systems [@Tyralis2019; @Biau2016]. In RF, a set of predictor variables (features) are used to predict the outcome of another variable (the predictant) through supervised learning algorithms, grouped as either regression or classification, depending on whether the variables are quantitative (i.e. numeric) or qualitative [@Breiman2001; @Tyralis2019]. 

The RF algorithm learns from many independent Classification And Regression Trees (CARTs) which undergo bootstrap-aggregating ("bagging") with randomization; meaning that no single tree includes all the data, which reduces over-fitting and improves prediction performance [@Breiman2001; @Tyralis2019; @Biau2016]. 

IN RF, many decision tree area created, each one generated by randomly sampling from the full data set (with replacement) and each tree is trained until only one possible solution remains (i.e., leaf nodes contain one deciding variable). For problems of regression (i.e., quantitative numeric variables, such as the data in this thesis), the forest prediction is the average of the individual trees predictions [@Tyralis2019; @Biau2016]. 

The relative importance of each feature is determined by assessing the accuracy of how well the predictant variable is anticipated in the absence of that feature. 

The R package RandomForest was built on Breiman's Random Forests algorithm. RandomForest was used to determine the relative importance of watershed characteristics and conditions in determining DOC concentrations and DOM character in across the six sites of the LWSA. 

  
[@Breiman2001]

### Methods



### Results

### Discussion

### Conclusions
