---
output: bookdown::word_document2
---

## Discussion of results in context of drinking water supply

```{r discussion-setup, warning = FALSE, message = FALSE, include = FALSE, package.startup.message = FALSE}

library(tidyverse)
library(knitr)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

__RQ.4.__   What are the implications for watershed management and future drinking water supply?

__Objective 4:__   Provide context of how results can be used to inform watershed management planning for wildfire reduction strategies and design of continued water quality monitoring for future inter-basin transfers.



* conflicting objectives and competing values (Peter Duinker's work)
  * managing temperate forests for timber removes carbon pools, managing for protection may increase the carbon, thus protection does not necessarily improve water quality. 
  * timber / carbon sequestration / water / biodiversity
  
* source water quality in rivers is unlikely to reflect the water at the intake tower
  * reservoir residence times
  * photodegradation
  * physiochemcial reactions and changes
  * biodegradation // transformation // bioproduction of NOM
  * the rivers introduce new material and new conditions (e.g. different temperatures, dissolved oxygen, carbonate for buffering or organic acids altering pH, new microbiota) the 
  * mixing is likely to change river source water -- a blanacing reservoir to stabilize between river and reservoir may be extremely useful (like how you add a bit of new water at a time for a goldfish in a bowl, to allow equilibration)
  * UV degradation is likely in lakes
  * while river water quality will not identify source water quality (pre-treatment) it is important to know IN TANDEM with Sooke Res limnology to anticipate potnetial problems based on conditions in each & knowledge of likely or possible interactions